# Page index
# If you add a page, you must also add it to the index here
nav:
#  - Home: 'index.md'
  - General:
    - About: '1-general/1-about.md'
    - Frequently Asked Questions: '1-general/2-faqs.md'
  - Getting Started:
    - Introduction to the Editor: '2-getting_started/1-introduction.md'
    - Introduction to Assets: '2-getting_started/2-assets_intro.md'
    - Introduction to Scripting: '2-getting_started/3-scripting_intro.md'
    - My First Game:
      - Basic Platformer: '2-getting_started/4-my_first_game/1-basic_platformer.md'
      - Dynamic Map: '2-getting_started/4-my_first_game/2-triggers.md'
      - Visual Overhaul: '2-getting_started/4-my_first_game/3-visuals.md'
      - Character Abilities: '2-getting_started/4-my_first_game/4-abilities.md'
      - Multiplayer Racing: '2-getting_started/4-my_first_game/5-multiplayer_racing.md'
  - Scripting:
    - Lua:
      - Introduction: '3-scripting/1-lua/1-introduction.md'
      - Primer: '3-scripting/1-lua/2-primer.md'
      - Resources: '3-scripting/1-lua/3-resources.md'
    - Best Practices: '3-scripting/2-best_practices.md'
    - Debugging: '3-scripting/3-debugging.md'
  - Project Workflow:
    - Project Setup: '4-project_workflow/1-project_setup.md'
    - Assets Workflow: '4-project_workflow/2-assets_workflow.md'
    - Scripts Workflow: '4-project_workflow/3-scripts_workflow.md'
    - Best Practices: '4-project_workflow/4-best_practices.md'
  - Tutorials:
    - Games:
      - First Person Shooters:
        - Free For All: '5-tutorials/1-games/1-fps/1-ffa.md'
        - Team Deathmatch: '5-tutorials/1-games/1-fps/2-tdm.md'
      - RPG: '5-tutorials/1-games/2-rpg.md'
      - Racing: '5-tutorials/1-games/3-racing.md'
    - Topics:
      - Editor:
        - Editor Windows: '5-tutorials/2-topics/1-editor/1-editor_windows.md'
        - Hotkeys: '5-tutorials/2-topics/1-editor/2-hotkeys.md'
        - GUI: '5-tutorials/2-topics/1-editor/3-gui.md'
        - Audio: '5-tutorials/2-topics/1-editor/4-audio.md'
        - Visual Effects: '5-tutorials/2-topics/1-editor/5-vfx.md'
        - Templates: '5-tutorials/2-topics/1-editor/6-templates.md'
        - Marketplace: '5-tutorials/2-topics/1-editor/7-marketplace.md'
        - Custom Properties: '5-tutorials/2-topics/1-editor/8-custom_properties.md'
      - Abstract:
        - Vectors: '5-tutorials/2-topics/2-abstract/1-vectors.md'
        - Advanced Vectors: '5-tutorials/2-topics/2-abstract/2-vectors_advanced.md'
        - Matrices: '5-tutorials/2-topics/2-abstract/3-matrices.md'
        - Raytracing: '5-tutorials/2-topics/2-abstract/4-raytracing.md'
  - Examples:
    - Main: '6-examples/links.md'
  - Community:
    - Links: '7-community/links.md'
  - Core API:
    - Coming Soon: '8-core_api/coming_soon.md'

# Additional data
extra:
  core_version: 0.0.x-prealpha # CORE editor version this documentation applies to

# If you make a PR, no need to change data below this point

# Base material theme with customizations
theme:
  name: 'material'
  custom_dir: 'theme'
  feature:
    tabs: false
  palette:
    primary: 'blue grey' # desired -> #20232a
    accent: 'amber' # desired -> #ff9000

extra:
  social:
    - type: 'discord' # unsupported
      link: 'ToDo'
    - type: 'reddit'
      link: 'ToDo'

markdown_extensions:
  - admonition # add info/warn/error admonitions
  - pymdownx.arithmatex # fancy math styling
  - pymdownx.betterem: # better bolding styles
      smart_enable: all
  - pymdownx.caret # insert and superscript
  - pymdownx.critic # editing allowed
  - pymdownx.details # admonition style details
  - pymdownx.emoji: # emojis
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite # inline code highlighting
  - pymdownx.magiclink # autolinks and shorthand
  - pymdownx.mark # highlights
  - pymdownx.smartsymbols # special symbols like arrows
  - pymdownx.superfences # tabbed content (e.g. with code)
  - pymdownx.tasklist: # task list
      custom_checkbox: true
  - pymdownx.tilde # strike-through
  - codehilite: # highlight code blocks
      guess_lang: false # language has to be defined explicitly
  - toc: # add linking to headers
      permalink: true

# Site name
site_name: CORE Docs

# Add repository for easy editing
repo_url: https://github.com/ManticoreGamesInc/Documentation

# Metadata
site_description: Documentation for the CORE Engine
site_author: Manticore