# Page index
# If you add a page, you must also add it to the index here
nav:
  - Home: 'index.md'
  - Introduction:
    - Main: '1-intro/index.md'
  - Getting Started:
    - Main: '2-getting-started/index.md'
  - Scripting:
    - Main: '3-scripting/index.md'
  - Project Workflow:
    - Main: '4-project-workflow/index.md'
  - Tutorials:
    - Main: '5-tutorials/index.md'
  - Examples:
    - Main: '6-examples/index.md'
  - Community:
    - Main: '7-community/index.md'
  - Core API:
    - Main: '8-core-api/index.md'

# Additional data
extra:
  core_version: 0.0.x-prealpha # CORE editor version this documentation applies to

# If you make a PR, no need to change data below this point

# Base material theme with customizations
theme:
  name: 'material'
  custom_dir: 'theme'

# Site name
site_name: CORE Docs

# Add repository for easy editing
repo_url: https://github.com/ManticoreGamesInc/Documentation

# Metadata
site_description: Documentation for the CORE Engine
site_author: Manticore